<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Helper\Address;

/** @var \Magento\Customer\Block\Form\Register $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/** @var Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $block->getData('addressHelper');
/** @var \Magento\Directory\Helper\Data $directoryHelper */
$directoryHelper = $block->getData('directoryHelper');
/** @var \Magento\Customer\ViewModel\Address\RegionProvider $regionProvider */
$regionProvider = $block->getRegionProvider();
$formData = $block->getFormData();
?>
<?php $displayAll = $block->getConfig('general/region/display_all'); ?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<form class="form create account form-create-account b2bregistration-form"
      action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
    <div class="form create account customer-details">
        <fieldset class="fieldset create info">
            <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
            <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">
            <?= $block->getLayout()
                    ->createBlock(\Magento\Customer\Block\Widget\Name::class)
                    ->setObject($formData)
                    ->setForceUseCustomerAttributes(true)
                    ->toHtml() ?>
            <?php if ($block->isNewsletterEnabled()): ?>
                <div class="field choice newsletter">
                    <input type="checkbox"
                        name="is_subscribed"
                        title="<?= $escaper->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>"
                        value="1"
                        id="is_subscribed"
                        <?php if ($formData->getIsSubscribed()): ?>checked="checked"<?php endif; ?>
                        class="checkbox">
                    <label for="is_subscribed" class="label">
                        <span><?= $escaper->escapeHtml(__('Sign Up for Newsletter')) ?></span>
                    </label>
                </div>
                <?php /* Extensions placeholder */ ?>
                <?= $block->getChildHtml('customer.form.register.newsletter') ?>
            <?php endif ?>

            <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
            <?php if ($_dob->isEnabled()): ?>
                <?= $_dob->setDate($formData->getDob())->toHtml() ?>
            <?php endif ?>

            <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?= $_taxvat->setTaxvat($formData->getTaxvat())->toHtml() ?>
            <?php endif ?>

            <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
            <?php if ($_gender->isEnabled()): ?>
                <?= $_gender->setGender($formData->getGender())->toHtml() ?>
            <?php endif ?>

            <div class="field required">
                <label for="email_address" class="label"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email"
                        name="email"
                        autocomplete="email"
                        id="email_address"
                        value="<?= $escaper->escapeHtmlAttr($formData->getEmail()) ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                        class="input-text"
                        data-mage-init='{"mage/trim-input":{}}'
                        data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
                <?php
                    $_streetValidationClass = $addressHelper->getAttributeValidationClass('street');
                ?>
                <?php 
                    $postcodeValidationClass = $addressHelper->getAttributeValidationClass('postcode');  
                ?>
                <?php
                    $cityValidationClass = $addressHelper->getAttributeValidationClass('city');
                ?>
                <?php
                    $regionValidationClass = $addressHelper->getAttributeValidationClass('region');
                ?>

                <div class="field street required">
                    <label for="street_1" class="label">
                        <span><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span>
                    </label>
                    <div class="control">
                        <textarea name="street[0]" id="street_1" value="<?= $escaper->escapeHtmlAttr($formData->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Shipping Address') ?>" class="input-textarea"  class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>" data-validate="{required:false}"></textarea>
                    </div>
                </div>
            <div class="customer_shipping">
                <div class="field zip required">
                    <label for="zip" class="label">
                        <span><?= /* @noEscape */ $block->getAttributeData('postcode') ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                            name="postcode"
                            value="<?= $escaper->escapeHtmlAttr($formData->getPostcode()) ?>"
                            title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                            id="zip"
                            class="input-text validate-zip-international
                                <?= $escaper->escapeHtmlAttr($postcodeValidationClass) ?>"
                                placeholder="<?= $escaper->escapeHtml(__('zip/postal')) ?>">
                    </div>
                </div>
                <div class="field country required">
                    <label for="country" class="label">
                        <span><?= /* @noEscape */ $block->getAttributeData('country_id') ?></span>
                    </label>
                    <div class="control">
                        <?= $block->getCountryHtmlSelect() ?>
                    </div>
                </div>
            </div>
            <div class="customer_shipping">
                <div class="field required">
                    <label for="city" class="label">
                        <span><?= /* @noEscape */ $block->getAttributeData('city') ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                            name="city"
                            value="<?= $escaper->escapeHtmlAttr($formData->getCity()) ?>"
                            title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                            class="input-text <?= $escaper->escapeHtmlAttr($cityValidationClass) ?>"
                            id="city"
                            placeholder="<?= $escaper->escapeHtml(__('city')) ?>">
                    </div>
                </div>
                <div class="field region required">
                    <label for="region_id" class="label">
                        <span><?= /* @noEscape */ $block->getAttributeData('region') ?></span>
                    </label>
                    <div class="control">
                        <select id="region_id"
                                name="region_id"
                                title="<?= /* @noEscape */ $block->getAttributeData('region') ?>"
                                class="validate-select region_id">
                            <option value="">
                                <?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?>
                            </option>
                        </select>
                        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'select#region_id') ?>
                        <input type="text"
                            id="region"
                            name="region"
                            value="<?= $escaper->escapeHtml($block->getRegion()) ?>"
                            title="<?= /* @noEscape */ $block->getAttributeData('region') ?>"
                            class="input-text <?= $escaper->escapeHtmlAttr($regionValidationClass) ?>">
                        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'input#region') ?>
                    </div>
                </div>
            </div>
        
            <?= $block->getChildHtml('fieldset_create_info_additional') ?>
        </fieldset>
        <?php if ($block->getShowAddressFields()): ?>
            <?php $cityValidationClass = $addressHelper->getAttributeValidationClass('city'); ?>
            <?php $postcodeValidationClass = $addressHelper->getAttributeValidationClass('postcode'); ?>
            <?php $regionValidationClass = $addressHelper->getAttributeValidationClass('region'); ?>
            <fieldset class="fieldset address">
                <input type="hidden" name="create_address" value="1" />
                <?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
                <?php if ($_fax->isEnabled()): ?>
                    <?= $_fax->setFax($formData->getFax())->toHtml() ?>
                <?php endif ?>

                <?php
                    $_streetValidationClass = $addressHelper->getAttributeValidationClass('street');
                ?>
                 <?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
                <?php if ($_telephone->isEnabled()): ?>
                    <?= $_telephone->setTelephone($formData->getTelephone())->toHtml() ?>
                <?php endif ?>
                  <?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
                <?php if ($_company->isEnabled()): ?>
                    <?= $_company->setCompany($formData->getCompany())->toHtml() ?>
                <?php endif ?>
                <div class="field tax_id">
                        <label for="tax_id" class="label"><span><?php /* @escapeNotVerified */ echo __('TAX ID') ?></span></label>
                    <div class="control">
                        <input type="text" name="tax_id" id="tax_id" title="<?php /* @escapeNotVerified */ echo __('TAX ID') ?>" />
                    </div>
                </div>
                <!-- <div class="field same_as_shipping">
                    <input type="checkbox" id="same_as_shipping" name="same_as_shipping">
                    <label for="same_as_shipping" class="label"><?php /* @escapeNotVerified */ echo __('Same as Shipping ') ?></label>
                </div> -->
                <div class="field billing_address">
                        <label for="billing_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Billing Address') ?></span></label>
                    <div class="control">
                        <textarea name="billing_address" id="billing_address" title="<?php /* @escapeNotVerified */ echo __('Billing Address') ?>" class="input-textarea" data-validate="{required:false}"></textarea>
                    </div>
                </div>
           
                <?php if ($addressHelper->isVatAttributeVisible()): ?>
                    <?php $_vatidValidationClass = $addressHelper->getAttributeValidationClass('vat_id'); ?>
                    <div class="field taxvat">
                        <label class="label" for="vat_id">
                            <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                        </label>
                        <div class="control">
                            <input type="text"
                                name="vat_id"
                                value="<?= $escaper->escapeHtmlAttr($formData->getVatId()) ?>"
                                title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                                class="input-text <?= $escaper->escapeHtmlAttr($_vatidValidationClass) ?>"
                                id="vat_id">
                        </div>
                    </div>
                <?php endif; ?>
            <div class="customer_billing">
                <div class="field zip_postal">
                        <label for="zip_postal" class="label"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
                    <div class="control">
                        <input type="text" name="zip_postal" id="zip_postal" title="<?php /* @escapeNotVerified */ echo __('') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('zip/postal') ?>" />
                    </div>
                </div>
                <div class="field country_billing">
                        <label for="country_billing" class="label"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
                    <div class="control">
                        <input type="text" name="country_billing" id="country_billing" title="<?php /* @escapeNotVerified */ echo __('') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('country') ?>" />
                    </div>
                </div>
            </div>

            <div class="customer_billing">
                <div class="field state">
                        <label for="state" class="label"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
                    <div class="control">
                        <input type="text" name="state" id="state" title="<?php /* @escapeNotVerified */ echo __('') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('state') ?>" />
                    </div>
                </div>
                <div class="field city_billing">
                        <label for="city_billing" class="label"><span><?php /* @escapeNotVerified */ echo __('') ?></span></label>
                    <div class="control">
                        <input type="text" name="city_billing" id="city_billing" title="<?php /* @escapeNotVerified */ echo __('') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('city') ?>" />
                    </div>
                </div>
            </div>
                <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                <?php if ($addressAttributes): ?>
                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                    <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                    <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                <?php endif;?>
                    <input type="hidden" name="default_billing" value="1">
                    <input type="hidden" name="default_shipping" value="1">
            </fieldset>

        <?php endif; ?>
        <fieldset class="fieldset details">
        <div class="field license_number">
            <label for="license_number" class="label"><span><?php /* @escapeNotVerified */ echo __('License Number') ?></span></label>
            <div class="control">
                <input type="text" name="license_number" id="license_number" title="<?php /* @escapeNotVerified */ echo __('License Number') ?>" />
            </div>
        </div>
        <div class="field customer_document">
            <label for="customer_document" class="label"><span><?php /* @escapeNotVerified */ echo __('Trade License') ?></span></label>
            <div class="control">
                <input type="file" name="customer[customer_document]" id="customer_document" title="<?php /* @escapeNotVerified */ echo __('Trade License') ?>" />
            </div>
        </div>
        

        <div class="field trn_number">
            <label for="poc_name" class="label"><span><?php /* @escapeNotVerified */ echo __('POC`s Name') ?></span></label>
            <div class="control">
                <input type="text" name="poc_name" id="poc_name" title="<?php /* @escapeNotVerified */ echo __('POC`s Name') ?>" />
            </div>
        </div>
        <div class="field poc_email">
            <label for="poc_email" class="label"><span><?php /* @escapeNotVerified */ echo __('poc`s Email') ?></span></label>
            <div class="control">
                <input type="text" name="poc_email" id="poc_email" title="<?php /* @escapeNotVerified */ echo __('poc`s Email') ?>" />
            </div>
        </div>
        <div class="field trn_number">
            <label for="designation" class="label"><span><?php /* @escapeNotVerified */ echo __('Designation') ?></span></label>
            <div class="control">
                <input type="text" name="designation" id="designation" title="<?php /* @escapeNotVerified */ echo __('Designation') ?>" />
            </div>
        </div>
        </fieldset>

        <fieldset class="fieldset create account"
            data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
            <div class="field trn_number">
                <label for="trn_number" class="label"><span><?php /* @escapeNotVerified */ echo __('TRN Number') ?></span></label>
                <div class="control">
                    <input type="file" name="customer[trn_number]" id="trn_number" title="<?php /* @escapeNotVerified */ echo __('TRN Number') ?>" />
                </div>
            </div>
            <div class="field license_expiry_date">
                <label for="license_expiry_date" class="label"><span><?php /* @escapeNotVerified */ echo __('License Expiry Date') ?></span></label>
                <div class="control">
                    <input type="date" name="license_expiry_date" id="license_expiry_date" title="<?php /* @escapeNotVerified */ echo __('License Expiry Date') ?>" />
                </div>
            </div>
            
            <div class="field password required">
                <label for="password" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
                <div class="control">
                    <input type="password" name="password" id="password"
                        title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>"
                        class="input-text"
                        data-password-min-length="<?=
                            $escaper->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                        data-password-min-character-sets="<?=
                            $escaper->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                        data-validate="{required:true, 'validate-customer-password':true}"
                        autocomplete="off">
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?= $escaper->escapeHtml(__('Password Strength')) ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                <?= $escaper->escapeHtml(__('No Password')) ?>
                            </span>
                        </div>
                    </div>
                </div>

            </div>
            <div class="field confirmation required">
                <label for="password-confirmation" class="label">
                    <span><?= $escaper->escapeHtml(__('Confirm Password')) ?></span>
                </label>
                <div class="control">
                    <input type="password"
                        name="password_confirmation"
                        title="<?= $escaper->escapeHtmlAttr(__('Confirm Password')) ?>"
                        id="password-confirmation"
                        class="input-text"
                        data-validate="{required:true, equalTo:'#password'}"
                        autocomplete="off">
                </div>
            </div>
            <div class="field choice" data-bind="scope: 'showPassword'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </fieldset>
    </div>
    <div class="actions-toolbar">
    <div class="primary">
        <button type="submit"
                class="action submit primary"
                title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>"
                id="send2"
            <?php if ($block->getButtonLockManager()->isDisabled('customer_create_form_submit')): ?>
                disabled="disabled"
            <?php endif; ?>>
            <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
        </button>
    </div>
    <div class="secondary">
        <a class="action back"
           href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('Back')) ?></span>
        </a>
        <button type="button"
                class="action cancel secondary"
                title="<?= $escaper->escapeHtmlAttr(__('Cancel')) ?>"
                onclick="window.location.href='<?= $escaper->escapeUrl($block->getBackUrl()) ?>'">
            <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
        </button>
    </div>
</div>
</form>

<?php $ignore = /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null';
$scriptString = <<<script
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = {$ignore};

    dataForm.mage('validation', {
script;
if ($_dob->isEnabled()):
    $scriptString .= <<<script
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
script;
else:
    $scriptString .= <<<script
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
script;
endif;
$scriptString .= <<<script
    }).find('input:text').attr('autocomplete', 'off');
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php if ($block->getShowAddressFields()): ?>
    <?php
    $regionJson = /* @noEscape */ $regionProvider->getRegionJson();
    $regionId = (int) $formData->getRegionId();
    $countriesWithOptionalZip = /* @noEscape */ $directoryHelper->getCountriesWithOptionalZip(true);
    ?>
<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "directoryRegionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $displayAll ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $regionJson ?>,
                "defaultRegion": <?= /* @noEscape */ $regionId ?>,
                "countriesWithOptionalZip": <?=  /* @noEscape */ $countriesWithOptionalZip ?>
            }
        }
    }
</script>
<?php endif; ?>
<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        },
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            },
            "Magento_Ui/js/core/app": {
                "components": {
                    "showPassword": {
                        "component": "Magento_Customer/js/show-password",
                        "passwordSelector": "#password,#password-confirmation"
                    }
                }
            }
        }
    }
</script>





