<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var collectSpan = jQuery('#import_span');

        jQuery('#productimport_button').click(function () {
            console.log('Product master triggered');
            var params = {};
            new Ajax.Request('<?php echo $block->getAjaxCheckUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    jQuery('#collect_message_span').text('');
                },
                onSuccess: function(response) {
                    collectSpan.find('.processing').hide();
                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success';
                        collectSpan.find('.collected').show();
                    }
                    jQuery('#import_message_span').text(resultText);
                    var json = response.responseJSON;
                    if (typeof json.time != 'undefined') {
                        jQuery('#apiconfig_general_ImportTime').val(json.time);
                        jQuery('#apiconfig_general_generated_report').val(json.message);
                    }
                }
            });
        });

    });
</script>

<div class="pp-buttons-container">
    <button id="<?= $block->getId() ?>" onclick="return false;" class="save primary">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
    <span class="collect-indicator" id="import_span">
        <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
        <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
        <span id="import_message_span"></span>
    </span>
</div>